DROP TABLE IF EXISTS NOMBREDETABLA;

CREATE TABLE NOMBREDETABLA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO NUMERIC (10, 2) NOT NULL
);